FROM alpine:latest AS build

ARG VERSION=0.1.1
ARG CHECKSUM

RUN apk add --no-cache tar && \
    mkdir /app && cd /app  
COPY sjp_versions.txt /tmp/sjp_versions.txt
RUN CHECKSUM=$(grep "^$VERSION:" /tmp/sjp_versions.txt | awk -F':' '{print $2}')
ADD --checksum=${CHECKSUM}  https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/${VERSION}.tar.gz/ /tmp/sjp.tar.gz
RUN tar -xzf /tmp/sjp.tar.gz --strip-components=1 -C /app


FROM python:3.12-slim

RUN mkdir /app
WORKDIR /app

COPY --from=build /app /app

RUN pip install -r requirements.txt --no-cache-dir

ENTRYPOINT ["python", "main.py"]
CMD ["--srcpath=/app/templates/", "--outpath=/app/build/"]