FROM alpine:latest AS build

ARG VERSION=main

RUN apk add --no-cache git && \
    mkdir /app && cd /app && \
    git clone https://github.com/MrDave/StaticJinjaPlus.git . && \
    git checkout ${VERSION}

FROM python:3.12-slim

RUN mkdir /app
WORKDIR /app

COPY --from=build /app /app

RUN pip install -r requirements.txt --no-cache-dir

ENTRYPOINT ["python", "main.py"]
CMD ["--srcpath=/app/templates/", "--outpath=/app/build/"]